infra/terraform/environments/dev/main.tf
infra/terraform/modules/service/README.md
infra/terraform/modules/service/ecs.tf
infra/terraform/modules/service/variables.tf

Add target groups and listener rules for the new ECS infrastructure.

feat(terraform): add target group and listener rules

---

.github/workflows/assets.yaml
.github/workflows/php.yaml
.github/workflows/security-app.yaml
infra/docker/api/Dockerfile
infra/docker/cli/Dockerfile
infra/docker/internal/Dockerfile
infra/docker/selfserve/Dockerfile
website/package-lock.json

Bumps the application to PHP 8.2.

feat(docker): upgrade to PHP 8.2

---

infra/docker/api/Dockerfile
infra/docker/cli/Dockerfile
infra/docker/internal/Dockerfile
infra/docker/selfserve/Dockerfile

feat(docker): disable OPCache locally

---

.github/dependabot.yaml
.github/workflows/ci.yaml

Splits the Terraform config in Dependabot. Dependabot was timing out.

ci: improve Dependabot stability

---

infra/terraform/accounts/nonprod/provider.tf
infra/terraform/accounts/prod/provider.tf
infra/terraform/environments/dev/provider.tf
infra/terraform/environments/int/provider.tf
infra/terraform/environments/prep/provider.tf
infra/terraform/environments/prod/provider.tf

Adds default tags to resources created by this repository. As this is a shared AWS account this will be useful to see what repository created resources.

feat(terraform): add default tags to resources

---

docs/app/data-retention/cleanup-organisation-user.md
docs/app/data-retention/cleanup-publication-police-data.md
docs/app/data-retention/custom-event-history-cleanup-procedure.md

Adds documentation for some overlooked procedures that were missed in the first pass

feat: add missed D&DR procedure documentation

---

infra/terraform/environments/dev/main.tf
infra/terraform/modules/service/README.md
infra/terraform/modules/service/batch.tf
infra/terraform/modules/service/variables.tf

feat(terraform): vol5504 add single batch job

---

infra/terraform/modules/service/batch.tf

feat(terraform): vol5506 fix compute environment

---

.github/workflows/docker.yaml
app/api/.gitignore
app/cdn/.gitignore
app/internal/.gitignore
app/selfserve/.gitignore
commitlint.config.ts

Refreshes the app version on the environments.

chore: trigger CD

---

compose.yaml

feat: migrate to `npm`

---

infra/terraform/environments/dev/main.tf

feat(terraform): vol5223 add all batch jobs

---

.github/workflows/cd.yaml

`succecss` -> `success` :trollface:

ci: fix typo in CD workflow

---

infra/terraform/accounts/nonprod/main.tf

feat(terraform): vol5237 create int environment backend

---

infra/terraform/environments/int/.terraform.lock.hcl
infra/terraform/environments/int/backend.tf
infra/terraform/environments/int/main.tf
infra/terraform/environments/int/variables.tf

feat(terraform): vol5237 create int environment

---

infra/terraform/environments/int/main.tf

fix(terraform): rename env to `int`

---

infra/terraform/environments/dev/main.tf

fix(terraform): Fix dodgy cron expressions
Related issue: https://dvsa.atlassian.net/browse/VOL-5223

fix(terraform): fix dodgy cron expressions

---

infra/terraform/modules/service/batch.tf

Related issue: https://dvsa.atlassian.net/browse/VOL-5223

fix(terraform): vol5223 add batch queue to eventbridge policy

---

docs/ci-cd.md

Adds a table of environments with purpose, stability, and test coverage.

docs: add environment purpose

---

CODEOWNERS

Adds codeowners per the proposed matrix.

docs: add code owners

---

app/api/config/autoload/local.php.dist
app/internal/config/autoload/config.global.php
app/internal/config/autoload/local.php.dist
app/selfserve/config/autoload/config.global.php
app/selfserve/config/autoload/local.php.dist

Missing bits to externalise the app logging level.

fix: externalise app log level

---

app/api/module/Api/src/Assertion/User/ManageUserSelfserve.php
app/api/module/Api/src/Domain/AuthAwareTrait.php
app/api/module/Api/src/Domain/CommandHandler/Auth/Login.php
app/api/module/Api/src/Domain/QueryHandler/Messaging/Conversations/AbstractConversationQueryHandler.php
app/api/module/Api/src/Domain/QueryHandler/User/RoleList.php
app/api/module/Api/src/Entity/User/Permission.php
app/api/module/Api/src/Entity/User/Role.php
app/api/module/Api/src/Entity/User/User.php
app/api/test/module/Api/src/Assertion/User/ManageUserSelfserveTest.php
app/api/test/module/Api/src/Domain/QueryHandler/BusRegSearchView/BusRegSearchViewContextListTest.php
app/api/test/module/Api/src/Domain/QueryHandler/BusRegSearchView/BusRegSearchViewListTest.php
app/api/test/module/Api/src/Domain/QueryHandler/Messaging/Conversations/ByLicenceTest.php
app/api/test/module/Api/src/Domain/QueryHandler/Messaging/Conversations/ByOrganisationTest.php
app/api/test/module/Api/src/Domain/QueryHandler/User/RoleListTest.php
app/api/test/module/Api/src/Domain/Validation/Handlers/Misc/IsOperatorUserTest.php
app/api/test/module/Api/src/Domain/Validation/Validators/CanAccessTxcInboxTest.php
app/api/test/module/Api/src/Domain/Validation/Validators/CanGovUkAccountTest.php
app/api/test/module/Api/src/Domain/Validation/Validators/CanMakeVerifyRequestTest.php
app/api/test/module/Api/src/Domain/Validation/Validators/CanVerifyTest.php
app/api/test/module/Api/src/Entity/User/UserEntityTest.php
app/internal/module/Olcs/src/Controller/Messages/AbstractConversationMessagesController.php
app/internal/module/Olcs/src/Controller/Operator/OperatorUsersController.php

Related issue: [VOL-5305](https://dvsa.atlassian.net/browse/VOL-5305)

feat: vol-5305 create transport consultant role

---

app/internal/composer.lock
app/internal/config/autoload/laminas-developer-tools.local.php.dist
app/selfserve/composer.lock
app/selfserve/config/autoload/laminas-developer-tools.local.php.dist

The fix has been merged. This removes the workaround and bumps `laminas-form`.

fix: remove `laminas-form` workaround

---

app/internal/composer.json
app/internal/composer.lock
app/selfserve/composer.json
app/selfserve/composer.lock

Bump dependencies to bring in required consts causing errors.

feat: bump common dependency

---

app/api/module/Api/src/Service/File/ContentStoreFileUploader.php
app/api/test/module/Api/src/Service/File/ContentStoreFileUploaderTest.php

To debug the current batch issues. This PR adds some logging in some likely areas.

fix(api): add status code to content store file uploader log

---

app/api/module/Snapshot/config/language/partials/cy_GB/markup-application_undertakings_signature_address_ni.phtml
app/api/module/Snapshot/config/language/partials/en_GB/markup-application_undertakings_signature_address_gb.phtml
app/api/module/Snapshot/config/language/partials/en_GB/markup-application_undertakings_signature_address_ni.phtml
app/api/module/Snapshot/config/language/partials/en_GB/markup-generic-return-address.phtml

Related issue: [VOL-5536](https://dvsa.atlassian.net/browse/VOL-5536)

feat: vol-5536 update addresses for Quarry House

---

packages/local-refresh/src/actions/ComposerInstall.ts
packages/local-refresh/src/actions/ResetDatabase.ts

optionally ignore-platform-reqs and add necessary hosts entry to liquibase container.

feat: offer ignore-platform-reqs option for composer. Add host alias

---

app/api/config/autoload/config-parameters.global.php
app/internal/config/autoload/config-paramater.global.php
app/selfserve/config/autoload/config-parameter.global.php

Related issue: [VOL-5765](https://dvsa.atlassian.net/browse/VOL-5765)

fix: cast log level params to int to fix CPMS error

---

app/api/composer.json
app/api/composer.lock
app/api/config/autoload/config-parameters.global.php
app/internal/composer.json
app/internal/composer.lock
app/internal/config/autoload/config-paramater.global.php
app/selfserve/composer.json
app/selfserve/composer.lock
app/selfserve/config/autoload/config-parameter.global.php

Bumps the dependency and fixes the config casts not being under the `config_parameters` key.

fix: bump `dvsa/laminas-config-cloud-parameters` and fix config structure

---

.github/workflows/assets.yaml

Migrate to `build:production` - includes minimization of assets.

ci: update asset build command to `build:production`

---

.github/workflows/cd.yaml

Add e2e test runs for dev/int CD. Work In Progress..
Related issue: [VOL-5263](https://dvsa.atlassian.net/browse/VOL-5263)

feat: add e2esmoke and full regression to workflow (WIP)

---

.github/workflows/cd.yaml

Call e2etest directly 
Related issue: [VOL-5263](https://dvsa.atlassian.net/browse/VOL-5263)

feat: add e2e tests to cd dev int vol 5263

---

.github/workflows/e2e-test-verification.yaml

feat: isolated e2e test workflow to verify params/outputs etc

---

.github/workflows/e2e-test-verification.yaml

chore: specify test type

---

.github/workflows/e2e-test-verification.yaml

Revert "chore: specify test type"

---

.github/workflows/e2e-test-verification.yaml

chore: remove input

---

app/internal/composer.json
app/internal/composer.lock
app/selfserve/composer.json
app/selfserve/composer.lock
app/selfserve/module/Olcs/src/Form/Model/Form/Vehicle/SwitchBoard.php

Fixes a mis-aligned submit button on Licence Vehicles page, bumps common to pull in another submission button alignment fix.
Related issue: [VOL-5830](https://dvsa.atlassian.net/browse/VOL-5830)
Related issue: [VOL-5829](https://dvsa.atlassian.net/browse/VOL-5829)

fix: submit button misalignment vol 5829 vol 5830

---

app/api/composer.lock
app/api/config/autoload/local.php.dist
app/api/module/Api/config/query-map.config.php
app/api/module/Api/config/validation-map/user.config.php
app/api/module/Api/src/Domain/Query/User/UserListSelfserve.php
app/api/module/Api/src/Domain/QueryHandler/User/OperatorAdminForOrganisationHasLoggedIn.php
app/api/module/Api/src/Domain/Repository/User.php
app/api/test/module/Api/src/Domain/QueryHandler/User/OperatorAdminForOrganisationHasLoggedInTest.php
app/api/test/module/Api/src/Domain/Repository/UserTest.php
app/selfserve/composer.lock
app/selfserve/module/Olcs/src/Controller/Lva/AbstractUndertakingsController.php

Cannot sign or submit application/variation unless an operator admin for the organisation has logged in.
Related issue: https://dvsa.atlassian.net/browse/VOL-5242

feat: cannot sign declaration unless op-adm for org has logged in

---

app/api/.gitignore
app/cdn/.gitignore
app/internal/.gitignore
app/selfserve/.gitignore

ci: trigger CD

---

.github/workflows/docker.yaml

Build docker image, scan it, then push it to avoid pushing failing images.

ci: refactor build and push steps to build, scan locally, then push

---

app/api/composer.lock
app/internal/composer.lock
app/selfserve/composer.lock

Update lock files for `olcs-transfer: v7.7.1`

chore: update lock files for `olcs-transfer: v7.7.1`

---

.github/workflows/cd.yaml
.github/workflows/ci.yaml

Use shared get app version action now located in dvsa/.github repo

refactor: use get-app-version from shared github repo

---

app/api/.gitignore
app/cdn/.gitignore
app/internal/.gitignore
app/selfserve/.gitignore

chore: trigger cd build/deploy/test

---

.github/workflows/cd.yaml
.github/workflows/deploy-environment.yaml
app/api/.gitignore
app/selfserve/.gitignore

chain cd workflow steps sequentially - avoid tests being skipped.

ci: chain dev deploy, dev test, int deploy steps

---

.github/workflows/cd.yaml
app/api/.gitignore

ci: trigger cd 241028

---

app/selfserve/module/Olcs/src/Controller/Lva/AbstractUndertakingsController.php

Related issue: [VOL-5886](https://dvsa.atlassian.net/browse/VOL-5886)

fix: temporary removal of check for operator admin login

---

app/cdn/package-lock.json
app/cdn/package.json

Related issue: [VOL-5816](https://dvsa.atlassian.net/browse/VOL-5816)

feat: bump govuk-frontend to 5.7.1 (royal coat of arms)

---

app/internal/composer.lock
app/selfserve/composer.lock

Updating `olcs-common` from `7.12` -> `7.13`

chore: update lock files

---

app/api/cli-config.php
app/api/composer.json
app/api/composer.lock
app/api/config/autoload/config.global.php
app/api/config/autoload/global.php
app/api/data/Migrations/Version20241030095525.php
app/api/migrations-db.php
app/api/migrations.php
app/api/module/Api/src/Entity/DigitalSignature.php
app/api/module/Api/src/Entity/Generic/ApplicationStep.php
app/api/module/Api/src/Entity/Messaging/MessagingMessage.php
app/api/module/Api/src/Entity/Messaging/MessagingUserMessageRead.php
app/api/module/Cli/config/module.config.php
docs/app/doctrine-migrations/_category_.json
docs/app/doctrine-migrations/overview.md

Integrate doctrine migrations into api. Work In Progress
Related issue: [VOL-5793](https://dvsa.atlassian.net/browse/VOL-5793)

feat: integrate doctrine migrations vol 5793

---

app/api/composer.lock

Bump symfony-filesystem to resolve insecure dependency alert in one of its dependencies.

fix: update dependency that had sub-dependency with security vuln

---

.github/workflows/assets.yaml
.github/workflows/cd.yaml
.github/workflows/deploy-account.yaml
.github/workflows/deploy-environment.yaml
.github/workflows/docker.yaml
app/api/.gitignore

Update workflows to match some renamed repository vatiables

refactor: update var names to match renamed repository vars

---

app/api/.gitignore

API file change to manual trigger CD

chore: trigger cd pipeline

---

.github/workflows/docker.yaml
app/api/.gitignore

Refactor docker workflow to use org var for AWS region

refactor: use org var for AWS region

---

.github/workflows/cd.yaml
.github/workflows/docker.yaml
app/api/.gitignore

Pass job queue params to test flow

refactor: pass test queue param inputs

---

app/api/.gitignore
app/selfserve/.gitignore

chore: update .gitignore

---

app/api/.gitignore

chore: trigger cd run to test vft

---

app/cdn/package-lock.json
app/cdn/package.json

chore: reset package and package lock to align

---

app/api/.gitignore

chore: cd trigger

---

app/api/.gitignore

release-as: 5.9.4-alpha.1
trigger release-please with pre-release version number

chore: bump

---

infra/terraform/accounts/nonprod/main.tf
infra/terraform/accounts/prod/main.tf

fixing issues with GithubOIDC provider assuming role in nonprod/prod

fix: trust policies for PR

---

app/api/module/Api/src/Entity/Pi/Pi.php
app/api/test/module/Api/src/Entity/Pi/PiEntityTest.php

Related issue: [VOL-5297](https://dvsa.atlassian.net/browse/VOL-5297)

fix: pi records without a case no longer throw errors VOL-5297

---

.snyk
app/api/.snyk
app/api/composer.lock
app/internal/composer.lock
app/selfserve/composer.lock

olcs-common to 7.16.0
olcs-transfer to 7.9.0

chore: olcs-common 7.16.0 olcs-transfer 7.9.0

---

app/api/module/Api/data/nr/xsd/3.4/CheckGoodRepute_Request.xsd
app/api/module/Api/data/nr/xsd/3.4/CheckGoodRepute_Response.xsd
app/api/module/Api/data/nr/xsd/3.4/CheckGoodRepute_Types.xsd
app/api/module/Api/data/nr/xsd/3.4/CheckTransportUndertakingData_Request.xsd
app/api/module/Api/data/nr/xsd/3.4/CheckTransportUndertakingData_Response.xsd
app/api/module/Api/data/nr/xsd/3.4/CheckTransportUndertakingData_Types.xsd
app/api/module/Api/data/nr/xsd/3.4/ErrorNotification.xsd
app/api/module/Api/data/nr/xsd/3.4/ErrorNotification_Types.xsd
app/api/module/Api/data/nr/xsd/3.4/Global_Types.xsd
app/api/module/Api/data/nr/xsd/3.4/NotifyCheckResult_Acknowledgement.xsd
app/api/module/Api/data/nr/xsd/3.4/NotifyCheckResult_Request.xsd
app/api/module/Api/data/nr/xsd/3.4/NotifyCheckResult_Response.xsd
app/api/module/Api/data/nr/xsd/3.4/NotifyCheckResult_Types.xsd
app/api/module/Api/data/nr/xsd/3.4/NotifyUnfitness_Acknowledgement.xsd
app/api/module/Api/data/nr/xsd/3.4/NotifyUnfitness_Request.xsd
app/api/module/Api/data/nr/xsd/3.4/NotifyUnfitness_Types.xsd
app/api/module/Api/data/nr/xsd/3.4/RoadSideInspection_Request.xsd
app/api/module/Api/data/nr/xsd/3.4/RoadSideInspection_Response.xsd
app/api/module/Api/data/nr/xsd/3.4/RoadSideInspection_Types.xsd

Version 3.4 xsds added to Api data folder
Related issue: [VOL-5800](https://dvsa.atlassian.net/browse/VOL-5800)

feat: added files for ERRU version 3.4 VOL-5800

---

app/api/module/Api/config/query-map.config.php
app/api/module/Api/config/validation-map/licence.config.php
app/api/module/Api/src/Domain/QueryHandler/Licence/ExistsWithOperatorAdmin.php
app/api/test/module/Api/src/Domain/QueryHandler/Licence/ExistsWithOperatorAdminTest.php

Add a check for existing licence plus whether it has operator admin
Related issue: [VOL-5955](https://dvsa.atlassian.net/browse/VOL-5955)

feat: add a check for existing licence plus whether it has operator admin

---

.github/workflows/run-liquibase.yaml

Correct param definitions to fix workflow

fix: liquibase workflow parameters

---

.github/workflows/run-liquibase.yaml
infra/docker/liquibase/Dockerfile

simplify docker build process, checkout etl as a workflow step not a build stage.

fix: simplify dockerfile stages and etl checkout

---

.github/workflows/run-liquibase.yaml
infra/docker/liquibase/Dockerfile

parameterize olcs-branch to checkout and run.

feat: parameterise etl ref

---

.github/workflows/run-liquibase.yaml

obtain a token from VOL github app to clone olcs-etl.

feat: retrieve token from app to clone olcs-etl

---

infra/terraform/modules/account/ecr.tf

Adding liquibase repo to ECR for liquibase releases

fix: add liquibase repo to ecr

---

app/api/module/Email/view/email/en_GB/html/user-registered-tc.phtml
app/api/module/Email/view/email/en_GB/plain/user-registered-tc.phtml

Related issue: [VOL-5963](https://dvsa.atlassian.net/browse/VOL-5963)

fix: correct email address in TC registration emails VOL-5963

---

app/api/composer.json
app/api/composer.lock

Related issue: [VOL-5952](LINK_TO_JIRA_TICKET)

chore: remove dependency on simplesamlphp/saml2 VOL-5952

---

app/api/module/Api/src/Domain/CommandHandler/Licence/ProposeToRevoke.php
app/api/module/Api/src/Entity/Organisation/Organisation.php
app/api/module/Cli/src/Domain/CommandHandler/MessageQueue/Consumer/CompaniesHouse/ProcessInsolvency.php
app/api/test/module/Api/src/Domain/CommandHandler/Licence/ProposeToRevokeTest.php
app/api/test/module/Api/src/Entity/Organisation/OrganisationEntityTest.php
app/api/test/module/Cli/src/Domain/CommandHandler/MessageQueue/Consumer/CompaniesHouse/ProcessInsolvencyTest.php

Related issue: [VOL-5959](https://dvsa.atlassian.net/browse/VOL-5959)

fix: operator admin checks now account for disabled users VOL-5959

---

app/cdn/assets/_js/components/wysiwyg.js
app/cdn/public/tinymce/plugins/spellchecker/includes/Engine.php

Related issue: [VOL-5907](https://dvsa.atlassian.net/browse/VOL-5907)

fix: change extra places where spellchecker language not defaulting to en_GB

---

app/internal/module/Olcs/src/Controller/Cases/Penalty/PenaltyController.php

Related issue: [VOL-5976](https://dvsa.atlassian.net/browse/VOL-5976)

fix: penalty info now displayed for erru cases VOL-5976

---

.idea/.name
app/api/config/autoload/config.global.php
app/api/config/autoload/local.php.dist
app/api/module/Api/src/Service/Nr/InrClientFactory.php
app/api/test/module/Api/src/Service/Nr/InrClientFactoryTest.php

Added AUTHORISATION HEADER TO REQUESTS TO INR SERVICE
Related issue: VOL-5802

feat(api): adding OAuth2 setup for INR calls

---

.github/workflows/deploy-account.yaml
.github/workflows/deploy-environment.yaml
infra/terraform/environments/dev/main.tf
infra/terraform/environments/int/main.tf

We have moved to a model of having more dedicated resource (both compute and memory) per terraform action. We should maximise the use of this to improve the speed of the workflow as the cost will remain the same. I have subsequently increased the parallelism for the terraform actions to align to this.

chore: increase parallelism for terraform deploy

---

.github/workflows/php.yaml

remove two conditionals causing skipped stages

fix: remove conditionals

---

app/api/module/Cli/src/Domain/CommandHandler/DataGovUkExport.php

Fix path string being added to csv attachment rather than intended csv data
Related issue: [VOL-5977](https://dvsa.atlassian.net/browse/VOL-5977)

fix: fixes path string being added to CSV uploaded/emailed to dft

---

app/cdn/assets/_js/components/wysiwyg.js
app/cdn/public/tinymce/plugins/spellchecker/includes/Engine.php

Revert "fix: change extra places where spellchecker language not defaulting to en_GB"

---

.github/workflows/cd.yaml
.github/workflows/run-liquibase.yaml

pass secret to called workflow.

fix: pass repo secret to called workflow

---

.github/workflows/run-liquibase.yaml

set shareIdentifier to value provided by platform

fix: set share identifier to volapp as advised

---

infra/terraform/modules/service/batch.tf

fix: incorrect secret arn

---

.github/workflows/cd.yaml
.github/workflows/run-liquibase.yaml

ensure liquibase step runs after docker and terraform acct steps.

fix: liquibase step dependencies

---

infra/docker/search/Dockerfile

fix: test search build and deployment

---

.github/workflows/cd.yaml
infra/docker/search/Dockerfile

again testing search build 

---

.github/workflows/cd.yaml
app/api/.gitignore

Related issue: [VOL-6024](https://dvsa.atlassian.net/browse/VOL-6024)

feat: run smoke on int first

---

.github/workflows/cd.yaml

fix: adding check to build-push docker

---

.github/workflows/cd.yaml

add missed permission and secrets block to prep rollback step

fix: add permissions and secrets for prep rollback

---

.github/workflows/cd.yaml
app/api/.gitignore
infra/docker/search/Dockerfile

trigger cd to test recent changes

chore: trigger cd run app/docker build

---

app/api/.gitignore
infra/docker/search/Dockerfile

chore: trigger cd run

---

.github/workflows/cd.yaml

Move liquibase step after environment TF

chore: reorder liquibase steps after terraform ensure reqd resources present

---

.github/workflows/cd.yaml

Add tf to liquibase step dependencies

fix: add tf to liquibase step dependencies

---

.github/workflows/cd.yaml
.github/workflows/run-liquibase.yaml
app/api/.gitignore

build liquibase container once per run

fix: only build liquibase once per run - submit batch for subsequent 3

---

infra/terraform/modules/service/README.md
infra/terraform/modules/service/batch.tf

feat: 5912 batch cloudwatch dashboard - initial

---

infra/terraform/modules/service/batch.tf

a fix for the dashboard formatting

fix: 5912 batch dashboard widget formatting

---

infra/terraform/modules/service/batch.tf

addressing format issue in previous failed workflow:
https://github.com/dvsa/vol-app/actions/runs/13135666879

fix: 5912 - batch dashboard - another formatting fix

---

infra/terraform/modules/service/README.md
infra/terraform/modules/service/batch-monitoring.tf
infra/terraform/modules/service/batch.tf

added additional metric filters for better visibility and separated batch.tf into batch.tf and batch-monitoring.tf to combat growing file size

feat: 5912 improved monitoring dashboard with additional metrics

---

.github/workflows/run-liquibase.yaml

chore: remove override

---

infra/terraform/modules/service/batch.tf

chore: db password arn formatting

---

.github/workflows/run-liquibase.yaml
infra/terraform/modules/service/batch.tf

Specify reqd arch for batch queue image pulls

chore: specify liquibase arch

---

app/selfserve/module/Olcs/src/Controller/Lva/AbstractUploadEvidenceController.php

Related issue: [VOL-5986](https://dvsa.atlassian.net/browse/VOL-5986)

fix: check for uploaded supporting evidence now works correctly

---

.github/workflows/docker.yaml
app/api/.gitignore

arm64 plugin swap needs checksum changing

chore: update checksum for plugin swap

---

infra/terraform/modules/service/batch-monitoring.tf
infra/terraform/modules/service/batch.tf

5912 - batch dashboard- adding missing log-group

---

infra/terraform/modules/service/batch-monitoring.tf
infra/terraform/modules/service/batch.tf

feat: 5912 batch dashboard - failed job count graph

---

.github/workflows/cd.yaml
app/internal/.gitignore

updated conditional to avoid liquibase step skip after dev

chore: trigger cd and add required liquibase conditionals

---

app/api/.gitignore

chore: update .gitignore for cd trigger

---

app/api/module/Api/src/Domain/CommandHandler/User/DeleteUserSelfserve.php
app/api/module/Api/src/Domain/CommandHandler/User/UpdateUser.php
app/api/module/Api/src/Domain/QueryHandler/User/User.php
app/api/test/module/Api/src/Domain/CommandHandler/User/DeleteUserSelfserveTest.php
app/api/test/module/Api/src/Domain/QueryHandler/User/UserTest.php
app/internal/composer.lock
app/internal/module/Admin/src/Controller/UserManagementController.php
app/internal/module/Admin/src/Form/Model/Fieldset/UserType.php
app/internal/module/Olcs/config/routes.config.php
app/internal/module/Olcs/src/Controller/Operator/OperatorUsersController.php
app/internal/module/Olcs/src/Data/Mapper/User.php
app/internal/module/Olcs/src/Table/Tables/operator-users.table.php
app/internal/test/Olcs/src/Data/Mapper/UserTest.php
app/selfserve/composer.lock

Related issue: [VOL-5918](https://dvsa.atlassian.net/browse/VOL-5918)
Related issue: [VOL-4718](https://dvsa.atlassian.net/browse/VOL-4718)

feat: internal users can't delete/modify last operator admin VOL-5918 VOL-4718

---

infra/terraform/environments/int/main.tf
infra/terraform/environments/prep/main.tf

Update batch job list for int/prep to include liquibase and search

chore: add missing liquibase and search batch task definitions to terraform

---

infra/docker/search/Dockerfile

chore: resolve trivy scan error by specifying nonroot user in searce before cmd

---

.github/workflows/cd.yaml
infra/terraform/modules/service/batch.tf

fix current errors with scheduling in int:
https://github.com/dvsa/vol-app/actions/runs/13308376865

fix: batch schedule per env names

---

infra/terraform/environments/int/main.tf
infra/terraform/environments/prep/main.tf
infra/terraform/modules/service/ecs-monitoring.tf

improving visibility of lb metrics

5908 service dashboard improvements

---

infra/terraform/modules/service/batch-monitoring.tf

fix for batch failures log group not receiving logs from EventBridge rule

fix: batch failures log group policy

---

app/selfserve/.gitignore

fix: add schedule to int queue jobs

---

app/api/composer.json
app/api/composer.lock
app/api/module/Api/src/Service/Nr/Filter/VrmFactory.php
app/api/test/module/Api/src/Service/Nr/Filter/VrmFactoryTest.php
app/internal/composer.json
app/internal/composer.lock
app/selfserve/composer.json
app/selfserve/composer.lock

Related issue: [VOL-5975](https://dvsa.atlassian.net/browse/VOL-5975)
[VOL-5975]: https://dvsa.atlassian.net/browse/VOL-5975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: transfer VRM filter now loaded correctly from filter manager VOL-5975

---

.github/workflows/run-liquibase.yaml
infra/terraform/modules/service/batch.tf

enable verbose queue output for batch and containers testing

chore: process queue verbosity

---

app/api/.gitignore

chore: update .gitignore for vft run

---

app/api/.gitignore

trigger cd

---

.github/workflows/cd.yaml
app/api/.gitignore

chore:Trigger cd vft use main

---

.github/workflows/docker.yaml
infra/terraform/modules/account/ecr.tf

fix: unplanned deleting of previous images

---

.github/workflows/docker.yaml
infra/terraform/modules/account/ecr.tf

fix: remove deleting of previous image - fix

---

infra/terraform/accounts/nonprod/main.tf
infra/terraform/accounts/prod/main.tf

let GH actions on prerelease branch assume aws OIDC roles

feat: allow prerelease branch action runs to assume oidc role

---

app/api/module/Api/src/Entity/Organisation/AbstractOrganisation.php

Related issue: [VOL-5988](https://dvsa.atlassian.net/browse/VOL-5988)
[VOL-5988]: https://dvsa.atlassian.net/browse/VOL-5988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: messaging file uploads now enabled by default VOL-5988

---

app/api/.gitignore

fix: update .gitignore

---

app/api/composer.lock
app/api/module/Api/src/Domain/CommandHandler/Bus/UpdateServiceDetails.php
app/api/module/Api/src/Entity/Bus/AbstractBusReg.php
app/api/module/Api/src/Entity/Bus/BusReg.php
app/api/test/module/Api/src/Domain/CommandHandler/Bus/UpdateServiceDetailsTest.php
app/api/test/module/Api/src/Entity/Bus/BusRegEntityTest.php
app/internal/composer.lock
app/internal/module/Olcs/src/Form/Model/Fieldset/BusServiceNumberAndType.php
app/selfserve/composer.lock

Related issue: [VOL-6054](https://dvsa.atlassian.net/browse/VOL-6054)
[VOL-6054]: https://dvsa.atlassian.net/browse/VOL-6054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add application complete date for bus reg records VOL-6054

---

app/api/config/autoload/local.php.dist
app/api/module/Api/config/command-map.config.php
app/api/module/Api/config/validation-map/cli.config.php
app/api/module/Api/config/validation-map/national-register.config.php
app/api/module/Api/src/Domain/CommandHandler/Cases/Si/SendResponse.php
app/api/module/Api/src/Domain/CommandHandler/Cases/Si/SendResponseFactory.php
app/api/module/Api/src/Service/Nr/InrClient.php
app/api/module/Api/src/Service/Nr/InrClientFactory.php
app/api/module/Api/src/Service/Nr/InrClientInterface.php
app/api/test/module/Api/src/Domain/CommandHandler/Cases/Si/SendResponseTest.php
app/api/test/module/Api/src/Service/Nr/InrClientFactoryTest.php

Related issue: [VOL-5801](https://dvsa.atlassian.net/browse/VOL-5801)
[VOL-5801]: https://dvsa.atlassian.net/browse/VOL-5801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: change INR factory and send msi response code, to allow reuse and fix connectivity VOL-5801

---

infra/terraform/modules/service/batch.tf

removed hardcoded value and replaced with conditional check + fixes
https://dvsa.atlassian.net/browse/VOL-6086

fix: hardcoded account value

---

app/api/.gitignore

fix: trigger bump

---

app/api/.gitignore

chore:bump-release

---

app/api/.gitignore

fix: another update .gitignore

---

app/api/composer.lock
app/api/module/Api/src/Domain/Repository/MessagingSubject.php
app/api/module/Api/src/Entity/Messaging/AbstractMessagingSubject.php
app/internal/composer.lock
app/selfserve/composer.lock

Related issue: [VOL-6069](https://dvsa.atlassian.net/browse/VOL-6069)
[VOL-6069]: https://dvsa.atlassian.net/browse/VOL-6069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: filter messaging subjects by active categories VOL-6069

---

.github/workflows/cd.yaml

Add pull from nonprod ecr/push to PROD ecr repo for images once dev/int testing complete

feat: push the container images proven by dev/int vfts to prod ECR repo

---

app/api/.gitignore

feat: updated gitignore

---

app/api/.gitignore

chore: empty commit

---

app/api/.gitignore

feat: update .gitignore

---

app/api/.gitignore

fix: update .gitignore for cd run

---

infra/docker/search/Dockerfile

Fix small issue causing docker linit error in CD runs

fix: tweak to supress linting error in CD pipeline

---

app/api/.gitignore

fix: testing search

---

.github/workflows/cd.yaml
infra/docker/search/Dockerfile

fix: cd workflow

---

infra/docker/search/Dockerfile

fix: update dockerfile

---

infra/docker/search/Dockerfile
infra/docker/search/entrypoint.sh

fix: search perms

---

.github/workflows/cd.yaml

specify ubuntu arm runner version

chore: update arm runner name

---

app/api/.gitignore

fix: update app file for rp bump

---

app/api/.gitignore

feat: untag-prod-ecr-latests-before-push

---

.github/workflows/cd.yaml
app/api/.gitignore

fix: bring change from main into cd.yaml and trigger a build

---

infra/terraform/environments/prep/main.tf

fix: update prep jobs

---

app/api/.gitignore

fix: trigger patch 1540

---

app/cdn/assets/_styles/themes/selfserve.scss

Custom css to hide form elements and add margins to headers.
Related issue: [5903](https://dvsa.atlassian.net/browse/VOL-5903)
https://github.com/dvsa/olcs-common/pull/204

feat: custom css for small vehicles

---

app/api/.gitignore

Release-As:  5.20.6-rc7
trigger pr

chore: release 5.20.6-rc7

---

infra/docker/search/entrypoint.sh

fix: search config paths

---

infra/docker/search/config/populate_indices.conf.dist
infra/docker/search/entrypoint.sh

fix: setting opensearch ecs compatibility and debug

---

infra/docker/search/config/populate_indices.conf.dist

fix: removed incorrect debug

---

infra/docker/search/Dockerfile
infra/docker/search/config/populate_indices.conf.dist

fix: updated jdbc library path

---

infra/docker/search/Dockerfile
infra/docker/search/config/templates/busreg.json

fix: search busreg template and duplicates

---

app/api/.gitignore

fix: update .gitignore trigger

---

app/api/.gitignore

fix: run vft again for tests

---

app/api/.gitignore

fix: vft no proxy fix test trigger

---

.lintstagedrc.mjs
infra/terraform/environments/prep/main.tf

Change ALB target for prep
Related issue: n/a

Fix: alb target for prep

---

.lintstagedrc.mjs
infra/terraform/environments/prep/main.tf

fix: lb host header prep

---

app/api/composer.lock
app/internal/composer.lock
app/selfserve/composer.lock

Related issue: [3304](https://dvsa.atlassian.net/browse/VOL-3304)

chore: dependencies bump

---

infra/docker/search/build.sh
infra/docker/search/config/generate-conf.sh
infra/docker/search/config/populate_indices.conf.dist
infra/docker/search/config/templates/address.json
infra/docker/search/entrypoint.sh

fix: testing opensearch automated rollover

---

app/cdn/assets/_styles/components/page-header.scss
app/selfserve/module/Olcs/view/layouts/base.phtml
app/selfserve/module/Olcs/view/partials/layout/top-level-navigation.phtml

Related issue: [VOL-6130](https://dvsa.atlassian.net/browse/VOL-6130)
[VOL-6130]: https://dvsa.atlassian.net/browse/VOL-6130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: updated GOV.UK header and nav to meet GDS standards

---

infra/docker/api/Dockerfile
infra/docker/cli/Dockerfile
infra/docker/internal/Dockerfile
infra/docker/selfserve/Dockerfile
infra/terraform/environments/prep/main.tf
infra/terraform/environments/prep/provider.tf

Backport some changes made on prerelease branch while testing containers, remove some tf not needed

chore: backport container dockerfile fixes to main, revert lb tf

---

app/api/.gitignore

fix: rebase and rerun

---

app/selfserve/module/Olcs/view/layouts/base.phtml

Related issue: [VOL-3304](https://dvsa.atlassian.net/browse/VOL-3304)
[VOL-3304]: https://dvsa.atlassian.net/browse/VOL-3304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: updated the wording on cookies banner to meet GDS standards

---

infra/terraform/environments/dev/main.tf
infra/terraform/environments/dev/variables.tf

removing search service since this is failing build atm

fix: remove search as currently this is failing

---

infra/terraform/environments/prep/main.tf
infra/terraform/modules/service/ecs.tf

This sets the listener rule to true, it doesn't achieve what it was designed too but we need to unpick the logic to resolve this at a later date.

fix: toggling listener_rule to true

---

app/api/.gitignore

fix: update .gitignore for new rp pr

---

app/internal/composer.lock
app/selfserve/composer.lock

Related issue: [VOL-6287](https://dvsa.atlassian.net/browse/VOL-6287)
[VOL-6287]: https://dvsa.atlassian.net/browse/VOL-6287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: latest version of olcs-common for T&C changes VOL-6287

---

app/api/.gitignore

fix: try new vft container

---

app/api/.gitignore

fix: update file for vft run

---

infra/terraform/environments/dev/main.tf
infra/terraform/environments/dev/variables.tf

fix: re-add search

---

app/api/.gitignore

fix: revert pp/prep lb target cnanges

---

app/selfserve/composer.lock
app/selfserve/module/Olcs/config/module.config.php

Related issue: [VOL-5871](https://dvsa.atlassian.net/browse/VOL-5871)
[VOL-5871]: https://dvsa.atlassian.net/browse/VOL-5871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: new route for main occupation criteria guidance page plus dependency bump

---

app/api/composer.lock
app/internal/composer.lock
app/selfserve/composer.lock

Bump olcs-transfer to bring in new PSV restricted journey
Related issue: [VOL-5882](https://dvsa.atlassian.net/browse/VOL-5882)
[VOL-5882]: https://dvsa.atlassian.net/browse/VOL-5882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update olcs-transfer for PSV restricted journey

---

infra/docker/search/config/templates/address.json

fix: search template policy

---

.gitignore
compose-custom.yaml.dist
packages/local-refresh/src/actions/CopyDockerComposeDist.ts

Related issue: [VOL-6308](https://dvsa.atlassian.net/browse/VOL-6308)
[VOL-6308]: https://dvsa.atlassian.net/browse/VOL-6308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: choice to develop using local copies of vol vendor repos VOL-6308

---

app/api/composer.lock
app/internal/composer.lock
app/selfserve/composer.lock

Related issue: [VOL-6115 + VOL-6298 ](https://dvsa.atlassian.net/browse/VOL-6298 + https://dvsa.atlassian.net/browse/VOL-6115)

chore: updated olcs-common/transfer for gov pay integration and new T&Cs

---

app/api/.gitignore

fix: update .gitignore for run

---

infra/terraform/environments/dev/main.tf

fix: search ecs update security group

---

infra/terraform/environments/dev/main.tf

increased limits to reflect current ec2 usage

fix: updated search resources

---

infra/docker/search/Dockerfile

fix: search create lastrun folder

---

infra/terraform/modules/service/batch.tf

fix: updated java memory limit

---

infra/terraform/environments/dev/main.tf
infra/terraform/modules/service/batch.tf

fix: search further bumping memory

---

infra/docker/search/config/populate_indices.conf.dist
infra/docker/search/config/templates/address.json

fix: testing rollover index policy

---

infra/docker/search/config/populate_indices.conf.dist
infra/docker/search/config/templates/address.json
infra/docker/search/config/templates/application.json
infra/docker/search/config/templates/busreg.json
infra/docker/search/config/templates/case.json
infra/docker/search/config/templates/irfo.json
infra/docker/search/config/templates/licence.json
infra/docker/search/config/templates/person.json
infra/docker/search/config/templates/psv_disc.json
infra/docker/search/config/templates/publication.json
infra/docker/search/config/templates/user.json
infra/docker/search/config/templates/vehicle_current.json
infra/docker/search/config/templates/vehicle_removed.json

fix: updated index templates 

---

app/internal/composer.lock
app/selfserve/composer.lock
app/selfserve/test/Olcs/src/FormService/Form/Lva/ApplicationBusinessDetailsTest.php
app/selfserve/test/Olcs/src/FormService/Form/Lva/LicenceBusinessDetailsTest.php
app/selfserve/test/Olcs/src/FormService/Form/Lva/VariationBusinessDetailsTest.php

…panies removal
Related issue: [VOL-6295, VOL-6298, VOL-6122](https://dvsa.atlassian.net/browse/VOL-6295 - https://dvsa.atlassian.net/browse/VOL-6122 - https://dvsa.atlassian.net/browse/VOL-6298)

chore: updated olcs-common for Ts&Cs, timezone fix and more

---

infra/docker/search/config/templates/address.json
infra/docker/search/config/templates/application.json
infra/docker/search/config/templates/busreg.json
infra/docker/search/config/templates/case.json
infra/docker/search/config/templates/irfo.json
infra/docker/search/config/templates/licence.json
infra/docker/search/config/templates/person.json
infra/docker/search/config/templates/psv_disc.json
infra/docker/search/config/templates/publication.json
infra/docker/search/config/templates/user.json
infra/docker/search/config/templates/vehicle_current.json
infra/docker/search/config/templates/vehicle_removed.json

fix: remove unused write index

---

app/api/.gitignore

fix: udate .gitignore

---

infra/docker/search/config/templates/address.json
infra/docker/search/config/templates/application.json
infra/docker/search/config/templates/busreg.json
infra/docker/search/config/templates/case.json
infra/docker/search/config/templates/irfo.json
infra/docker/search/config/templates/licence.json
infra/docker/search/config/templates/person.json
infra/docker/search/config/templates/psv_disc.json
infra/docker/search/config/templates/publication.json
infra/docker/search/config/templates/user.json
infra/docker/search/config/templates/vehicle_current.json
infra/docker/search/config/templates/vehicle_removed.json

fix: address search alias issues

---

infra/docker/search/config/templates/address.json
infra/docker/search/config/templates/application.json
infra/docker/search/config/templates/busreg.json
infra/docker/search/config/templates/case.json
infra/docker/search/config/templates/irfo.json
infra/docker/search/config/templates/licence.json
infra/docker/search/config/templates/person.json
infra/docker/search/config/templates/psv_disc.json
infra/docker/search/config/templates/publication.json
infra/docker/search/config/templates/user.json
infra/docker/search/config/templates/vehicle_current.json
infra/docker/search/config/templates/vehicle_removed.json

fix: remove duplicates search

---

app/internal/composer.lock
app/selfserve/composer.lock

The update contains two tickets: one for a T&Cs change, and the other for the removal of a defective query that’s breaking a ticket related to removing the subsidiary companies section from the business details page for a PSV application/licence.
Related issue: [VOL-6122 / VOL-6319](https://dvsa.atlassian.net/browse/VOL-6122 -- https://dvsa.atlassian.net/browse/VOL-6319)

feat: updated olcs-common for Ts&Cs change and remove defective query

---

app/api/.gitignore

fix: test run 2005

---

infra/terraform/environments/int/main.tf
infra/terraform/environments/int/variables.tf

feat: deploy int search

---

infra/terraform/environments/prep/main.tf

chore: swap LBs for PREP/PP

---

app/internal/composer.lock
app/selfserve/composer.lock

Related issue: [VOL-6370](https://dvsa.atlassian.net/browse/VOL-6370)
[VOL-6370]: https://dvsa.atlassian.net/browse/VOL-6370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: update to olcs-common fixes continuations form stored cards issue VOL-6370

---

app/api/composer.lock
app/internal/composer.lock
app/selfserve/composer.lock

Related issue: [VOL-5882](https://dvsa.atlassian.net/browse/VOL-5882)
[VOL-5882]: https://dvsa.atlassian.net/browse/VOL-5882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: olcs-trasfer update to bring in latest PSV journey fixes VOL-5882

---

infra/docker/search/config/populate_indices.conf.dist

fix: search index timestamps

---

infra/terraform/environments/prep/main.tf

fix: switch lb rule for prep

---

infra/docker/search/config/generate-conf.sh
infra/docker/search/config/populate_indices.conf.dist
infra/docker/search/config/py/getIndexSize.py
infra/docker/search/config/py/indexWithoutAlias.py
infra/docker/search/config/py/modifyAliases.py
infra/docker/search/entrypoint.sh

fix: switching to reindex script

---

app/api/.gitignore
app/internal/.gitignore
app/selfserve/.gitignore

chore: trigger docker builds and vft run

---

app/api/module/Api/src/Domain/CommandHandler/Document/DeleteDocument.php
app/api/module/Api/src/Domain/CommandHandler/Email/SendUserRegistered.php
app/api/module/Api/src/Domain/QueryHandler/User/OperatorAdminForOrganisationHasLoggedIn.php
app/api/module/Api/src/Domain/Repository/MessagingSubject.php
app/api/module/Api/src/Entity/User/User.php
app/api/module/Api/src/Service/Nr/MsiResponse.php
app/api/module/Cli/config/module.config.php
app/api/module/DocumentShare/src/Service/WebDavClient.php
app/api/test/module/Api/src/Domain/CommandHandler/User/CreateUserSelfserveTest.php
app/api/test/module/Api/src/Domain/CommandHandler/User/RegisterConsultantAndOperatorTest.php
app/api/test/module/Api/src/Domain/QueryHandler/Licence/ExistsWithOperatorAdminTest.php
app/api/test/module/Api/src/Domain/QueryHandler/User/OperatorAdminForOrganisationHasLoggedInTest.php
app/api/test/module/Cli/src/Domain/CommandHandler/DataGovUkExportTest.php
app/internal/module/Olcs/src/Controller/Cases/Penalty/PenaltyController.php
app/selfserve/module/Olcs/src/Controller/ConsultantRegistrationController.php
app/selfserve/module/Olcs/src/Controller/Lva/AbstractUploadEvidenceController.php
app/selfserve/module/Olcs/src/Controller/Mapper/CreateAccountMapper.php
app/selfserve/module/Olcs/src/Controller/OperatorRegistrationController.php
app/selfserve/module/Olcs/src/Controller/UserRegistrationController.php
app/selfserve/module/Olcs/src/Form/Model/Fieldset/ContinueButton.php
app/selfserve/module/Olcs/src/Form/Model/Fieldset/ExistingOperatorLicenceApplication.php
app/selfserve/module/Olcs/src/Form/Model/Fieldset/OperatorRegistrationButtonGroup.php
app/selfserve/module/Olcs/src/Form/Validator/UniqueConsultantDetails.php
app/selfserve/module/Olcs/src/Mvc/CookieBannerListener.php
app/selfserve/module/Olcs/src/Mvc/TermsAgreedListener.php
app/selfserve/module/Olcs/src/Session/ConsultantRegistration.php
app/selfserve/test/Olcs/src/Controller/ConsultantRegistrationControllerTest.php
app/selfserve/test/Olcs/src/Controller/UserControllerTest.php
app/selfserve/test/Olcs/src/Controller/UserRegistrationControllerTest.php

clear phpcs errors in api/selfserve/internal for CI pipeline static analysis restoration

fix: cleaned up phpcs errors for green ci

---

.github/workflows/php.yaml
app/api/.gitignore
app/api/module/Api/src/Domain/CommandHandler/Bus/Ebsr/AbstractProcessPack.php
app/api/psalm.xml.dist
app/internal/.gitignore
app/internal/psalm.xml.dist
app/selfserve/.gitignore
app/selfserve/phpstan.neon.dist

chore: cd trigger 0611 1128

---

app/internal/.gitignore

triggering full regression vft to verify 3rd party test flow

chore: trigger cd to check govuk vft flow

---

.github/workflows/docker.yaml
app/internal/.gitignore

Update shasum in githib workflow after upstream plugin release invalidated current one

chore: update plugin checksum notation action

---

app/selfserve/.gitignore

chore: update .gitignore for vft/mailpit test

---

app/api/.gitignore

chore:Update .gitignore

---

app/api/.gitignore

chore: trigger-cd-wed-18-1540

---

app/api/.gitignore

chore: trigger-cd-19-jun-11-1155

---

infra/terraform/environments/prep/main.tf

fix: disable listener rule prep

---

app/api/.gitignore

fix: trigger-cd-20-july-1153

---

infra/terraform/accounts/nonprod/provider.tf
infra/terraform/accounts/prod/provider.tf

fix: limit tf provider version

---

app/api/.gitignore

chore: trigger-cd-26-jun-915

---

app/api/.gitignore

chore:trigger-cd-26-jun-1400

---

app/api/.gitignore

chore: trigger-cd-7-july-12

---

app/api/.gitignore

chore: trigger-cd-jul-8-1725

---

app/api/.gitignore

chore: cd run

---

app/api/.gitignore

chore: trigger cd 12

---

app/api/composer.lock
app/api/module/Api/src/Entity/Application/AbstractApplicationTracking.php
app/api/module/Api/src/Entity/Application/ApplicationTracking.php
app/api/test/module/Api/src/Entity/Application/ApplicationTrackingEntityTest.php
app/internal/composer.lock
app/selfserve/composer.lock

Related issue: [VOL-6466](https://dvsa.atlassian.net/browse/VOL-6466)
[VOL-6466]: https://dvsa.atlassian.net/browse/VOL-6466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add application tracking fields in prep for new internal psv journey VOL-6466 VOL-5882

---

infra/terraform/environments/prep/main.tf

chore: update main.tf

---

app/api/module/Api/src/Domain/CommandHandler/Correspondence/ProcessInboxDocuments.php
app/api/test/module/Api/src/Domain/CommandHandler/Correspondence/ProcessInboxDocumentsTest.php

Related issue: [VOL-6467](https://dvsa.atlassian.net/browse/VOL-6467)
[VOL-6467]: https://dvsa.atlassian.net/browse/VOL-6467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: correspondence inbox messages are no longer printed VOL-6467

---

app/api/.gitignore

fix: trigger cd prereleas1

---

app/api/.gitignore

chore: trigger release please prerelease 0806

---

.github/workflows/cd.yaml
app/api/.gitignore

fix: bumping .gitignore for release-please bump

---

app/api/.gitignore

Trigger release please prerelease 0811

---

infra/terraform/environments/prod/main.tf
infra/terraform/modules/service/batch.tf

fix: prod apply param refs

---

infra/terraform/modules/service/ecs.tf

fix: update proving lb rule priority

---

infra/terraform/environments/prod/main.tf

fix: ecs lb rule routing

---

app/api/.gitignore

fix: bumping git ignore

---

infra/terraform/modules/service/ecs.tf

fix: upped proving lb rule priority

---

infra/terraform/environments/dev/main.tf
infra/terraform/environments/int/main.tf
infra/terraform/environments/prep/main.tf
infra/terraform/environments/prod/main.tf
infra/terraform/modules/service/README.md
infra/terraform/modules/service/ecs.tf

Attempting to amend ecs and environment main.tf files to define desired_count for services

fix: add try and desired_count to ecs module

---

.github/workflows/security-app.yaml
app/internal/.snyk

Snyk temporary ignore for v.low risk CVE while upstream project resolves

chore: snooze snyk alert while project devs resolve the CVE

---

.github/workflows/ci.yaml
infra/docker/cli/Dockerfile

Add lpr via cups-client package to cli container
Related issue: [VOL-6568](https://dvsa.atlassian.net/browse/VOL-6568)
[VOL-6568]: https://dvsa.atlassian.net/browse/VOL-6568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add cups-client to get lpr command in batch container

---

app/api/config/autoload/config.global.php
app/api/config/autoload/local.php.dist
app/api/module/Api/config/module.config.php
app/api/module/Api/src/Domain/CommandHandler/PrintScheduler/PrintJob.php
app/api/module/Api/src/Service/ConvertToPdf/ConvertToPdfFactory.php
app/api/module/Api/src/Service/ConvertToPdf/ConvertToPdfInterface.php
app/api/module/Api/src/Service/ConvertToPdf/GotenbergClient.php
app/api/module/Api/src/Service/ConvertToPdf/WebServiceClient.php
compose.yaml
docs/infrastructure/services/_category_.json
docs/infrastructure/services/pdf-converter.md
infra/terraform/environments/dev/main.tf
infra/terraform/environments/int/main.tf
infra/terraform/environments/prep/main.tf
infra/terraform/environments/prod/main.tf
infra/terraform/modules/service/README.md
infra/terraform/modules/service/ecs.tf

Replace Windows PDF Converter with Gotenberg (VOL-1571)
This PR implements an interim solution for the VOL-1571 "Renderer 2.0" epic by replacing the legacy Windows EC2-based PDF conversion service with Gotenberg, a modern containerized alternative. This change eliminates Windows server dependencies, reduces licensing costs, and addresses critical security  vulnerabilities while maintaining full compatibility with existing RTF templates.

feat: non-windows, containerised pdf renderer solution proposal

---

app/api/module/Api/src/Domain/CommandHandler/ContinuationDetail/GenerateChecklistReminder.php
app/api/test/module/Api/src/Domain/CommandHandler/ContinuationDetail/GenerateChecklistReminderTest.php

Related issue: [VOL-6539](https://dvsa.atlassian.net/browse/VOL-6539)
[VOL-6539]: https://dvsa.atlassian.net/browse/VOL-6539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: continuation checklists no longer print automatically VOL-6539

---

infra/terraform/modules/service/ecs.tf

fix: renderer lb rule conditional syntax

---

infra/terraform/modules/service/ecs.tf

fix: remove proving renderer rule

---

.github/workflows/printpit.yaml
infra/docker/printpit/Dockerfile

Resolve hadolint issues in deploy pipeline

fix: resolve build pipeline scanning issues

---

app/internal/module/Olcs/view/layout/partials/global-header.phtml

Related issue: [VOL-6593](https://dvsa.atlassian.net/browse/VOL-6593)
[VOL-6593]: https://dvsa.atlassian.net/browse/VOL-6593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: updated Internal heading to read VOL instead of OLCS - VOL-6593

---

app/internal/module/Olcs/view/layout/partials/global-header.phtml

Revert "feat: updated Internal heading to read VOL instead of OLCS - VOL-6593"

---

infra/docker/cli/Dockerfile

chore(docker): install mysql and aws cli

---

app/api/module/Api/src/Entity/Application/AbstractApplication.php
app/api/module/Api/src/Entity/Cases/AbstractComplaint.php
app/api/module/Api/src/Entity/Cases/AbstractStatement.php
app/api/module/Api/src/Entity/CommunityLic/AbstractCommunityLicSuspension.php
app/api/module/Api/src/Entity/CommunityLic/AbstractCommunityLicSuspensionReason.php
app/api/module/Api/src/Entity/CommunityLic/AbstractCommunityLicWithdrawal.php
app/api/module/Api/src/Entity/ContactDetails/AbstractContactDetails.php
app/api/module/Api/src/Entity/Fee/AbstractFeeTransaction.php
app/api/module/Api/src/Entity/Licence/AbstractLicence.php
app/api/module/Api/src/Entity/Licence/AbstractLicenceVehicle.php
app/api/module/Api/src/Entity/Messaging/AbstractMessagingMessage.php
app/api/module/Api/src/Entity/Opposition/AbstractOpposer.php
app/api/module/Api/src/Entity/Opposition/AbstractOpposition.php
app/api/module/Api/src/Entity/Organisation/AbstractOrganisation.php
app/api/module/Api/src/Entity/User/AbstractUser.php
app/api/module/Api/src/Entity/User/AbstractUserPasswordReset.php
app/api/module/Cli/src/Service/EntityGenerator/TypeHandlers/RelationshipTypeHandler.php

fixes some properties the generator was not adding to some entities

fix: fixes annotation properties the generator missed

---

.github/workflows/cd.yaml

fix: CD workflow errors

---

.github/workflows/deploy-and-test.yaml

fix: deploy and test fixes
