dvsa/vol-app

.github/workflows/cd.yaml
.github/workflows/ci.yaml
infra/docker/cli/Dockerfile
infra/docker/cli/php.ini
infra/terraform/modules/account/ecr.tf

Adds an image template for the CLI application.
Related issue: https://dvsa.atlassian.net/browse/VOL-4801

feat: add CLI image

---

infra/terraform/environments/dev/main.tf
infra/terraform/modules/service/README.md
infra/terraform/modules/service/cdn.tf
infra/terraform/modules/service/ecs.tf
infra/terraform/modules/service/variables.tf

Moves the CDN to behind the VPN. Moves the `A` record to the private zone.
Related issue: https://dvsa.atlassian.net/browse/VOL-5380

feat(terraform): move `A` record for CDN to private zone

---

.github/dependabot.yaml

Adds Terraform related directories to the Dependabot config
Related issue: https://dvsa.atlassian.net/browse/VOL-5369

chore: add Terraform directories to Dependabot

---

infra/docker/selfserve/selfserve.conf

Adds an nginx redirect for GOV.UK One Login redirects.
Related issue: https://dvsa.atlassian.net/browse/VOL-5337

feat(docker): add GOV.UK One Login redirect to nginx

---

infra/terraform/.tflint.hcl

Bumps the TFLint AWS ruleset to 0.31.0.

chore: bump `tflint` AWS ruleset to `v0.31.0`

---

.github/workflows/cd.yaml
compose.yaml
infra/terraform/modules/account/github.tf
infra/terraform/modules/github/README.md
infra/terraform/modules/github/main.tf
infra/terraform/modules/github/variables.tf

The GitHub module tweaks that make it more re-usable across different projects. The eventual aim is to make this a re-usable module outside of this repository.

fix(terraform): make the GitHub module more re-usable

---

.github/workflows/assets.yaml
.github/workflows/deploy-account.yaml
.github/workflows/deploy-environment.yaml
.github/workflows/docker.yaml
.github/workflows/php.yaml

By default `actions/checkout` uses a fetch depth of 1. This isn't appropriate if the `ref` is older than the last commit.

ci: add `fetch-depth` to re-usable workflow checkout

---

.github/workflows/docker.yaml

Removes the duplicate `latest` tag of application images. Most registries detected this as duplicate but this cleans up that bit to not rely on the de-duplication of third parties.

ci: remove duplicate `latest` tag push

---

infra/terraform/environments/dev/main.tf

feat(terraform): vol5506 fix variables

---

.github/workflows/cd.yaml
.github/workflows/ci.yaml
.github/workflows/deploy-environment.yaml
infra/terraform/modules/service/batch.tf
infra/terraform/modules/service/cdn.tf
infra/terraform/modules/service/ecs.tf

- Add `cli-image-tag` to CI/CD to allow the CLI image to be deployed individually.
- Prefix batch job names with environment prefix.
- Add environment variables to batch jobs.
- Change runtime platform to ARM64 of batch jobs.
- Consolidate the batch queues to a single one - this may change in the future but for now is fine.

fix(terraform): tweak batch config

---

compose.yaml
infra/docker/cli/Dockerfile

Adds the execute permission bit to the Laminas binary in the CLI image.

fix(docker): add execute permission to Laminas binary in CLI image

---

infra/terraform/modules/service/batch.tf

Adds a `jobRoleArn` for the application when calling AWS via—the SDK.
Update the CloudWatch log name to include environment.

fix(terraform): add `jobRoleArn` to Batch containers

---

.github/workflows/deploy-account.yaml
.github/workflows/deploy-environment.yaml

The maximum input size is ~64KB.
The maximum PR comment size is ~64KB.
The plan can be larger than this, so we need to truncate it.
Saving the plan to a file allows JavaScript to truncate this and avoid it being too large for the inputs and the PR comment.

ci: truncate long Terraform plans

---

app/cdn/Gruntfile.js

`govuk-frontend` v5 has moved the assets to `node_modules/govuk-frontend/dist/govuk/assets/`.
https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md#update-package-file-paths-for-assets-such-as-images-and-fonts

fix(cdn): point to new `govuk-frontend` asset path

---

.github/workflows/docker.yaml

Scope the Docker cache by image. The hope is that this reduces the cache misses while building these images.

ci: scope Docker cache by image

---

infra/terraform/modules/service/README.md
infra/terraform/modules/service/cdn.tf

The assets are hardcoding in `/static/public/` in the path.
We need to rewrite the URI to remove it as the new assets doesn't follow the unnecessary directory structure.
New asset path: `/assets/images/favicon.ico` vs old asset path: `/static/public/assets/images/favicon.ico`.
This function will provide support for both while EC2 and ECS are running in parallel.
This can be removed once we remove EC2 infrastructure and the assets no longer have the path prefix.

feat(terraform): add CloudFront function to rewrite legacy assets path

---

infra/terraform/modules/service/batch.tf

The plans are all dirty with:
```tf
~ resource "aws_batch_job_queue" "this" {
id                    = "arn:aws:batch:eu-west-1:054614622558:job-queue/vol-app-dev-default"
name                  = "vol-app-dev-default"
+ tags                  = {}
}
```
This looks to be caused by a provider bug: `terraform-provider-aws/issues/38173`. This only affects certain resources, `aws_batch_job_queue` being one of them it seems.
This PR adds a tag to clean up the plans.

fix(terraform): add Batch queue tags to clean plan

---

infra/terraform/modules/service/cdn.tf

The VOL app is trying to make a CORS request for the GOV.UK JavaScript. This adjusts the managed policy on CloudFront to pass CORS headers.

fix(terraform): adjust `response_headers_policy_name` for CORS requests

---

infra/terraform/environments/dev/main.tf

Fixes the permission denied when sending emails on `dev`.
Related issue: https://dvsa.atlassian.net/browse/VOL-5681

fix(terraform): allow `dev` environment to push to S3 email bucket

---

infra/terraform/modules/service/ecs.tf

ClamAV is being killed due as the containers do not seemingly have enough memory.
The containers were taking a share of the overall task definition CPU/memory. This is no longer required while the tasks have a single container running inside them.
This may require some tweaking afterwards.

fix(terraform): remove CPU/Memory division for containers

---

app/cdn/assets/_styles/components/radios.scss
app/cdn/assets/_styles/themes/selfserve.scss

SCSS override to fix hints defined inside radio labels.
Related issue: [VOL-5685](https://dvsa.atlassian.net/browse/VOL-5685)

fix: add style to fix radio hint alignment issue

---

infra/terraform/modules/service/batch.tf

fix(terraform): Fix json input for batch schedules
Related issue: https://dvsa.atlassian.net/browse/VOL-5223

fix(terraform): fix json input for batch schedules

---

infra/terraform/modules/service/batch.tf

The queue has been set up with a fair share scheduling policy, so the batch jobs need a share identifier and priority to be submitted. I've set defaults for now but we can make them more specific further down the line.
Annoyingly there is an option to add a scheduling priority to a job definition in terraform, but this option does not yet exist in the batch module, so we need to set an override in the scheduling instead.
Related issue: https://dvsa.atlassian.net/browse/VOL-5223

fix(terraform): vol5223 give batch jobs a priority and share identifier

---

infra/terraform/modules/service/cdn.tf

The S3 bucket is re-used so cannot limit by specific distributions. This PR removes that condition.

fix(terraform): remove specific CloudFront S3 policy condition

---

infra/terraform/modules/account/README.md
infra/terraform/modules/account/main.tf
infra/terraform/modules/service/README.md
infra/terraform/modules/service/cdn.tf

Moves the `aws_s3_bucket_policy` to account level. The S3 bucket itself is shared so makes sense to be done once instead of per environment.

feat(terraform): move `aws_s3_bucket_policy` to account level

---

website/docusaurus.config.ts

The base URL changes when pages are made public. This updates that now the pages are working again.

docs: update `baseUrl` to `vol-app`

---

compose.yaml
docs/app/local-setup.md
docs/infrastructure/docker/overview.md
packages/local-refresh/actions/ResetDatabase.ts

- Mount `olcs-etl` directory to DB container.
- Add docs on how to customise the relative path to the `olcs-etl` project.

fix: fix local setup

---

.github/workflows/php.yaml
.github/workflows/security-app.yaml

Removes the `path` from the checkout. No longer required now a mono-repository.

ci: fix path checkout

---

compose.yaml

Resolve etl refresh not resolving host.docker.internal alias.

fix: extra-hosts entry for non Docker Desktop systems

---

.github/workflows/docker.yaml

Post mono-repository the short SHA is now 10 characters long instead of the default 7 characters due to the number of commits. The docker/metadata-action is not using git to work out the SHA and truncates the full SHA to 7 characters (https://github.com/docker/metadata-action/blob/60a0d343a0d8a18aedee9d34e62251f752153bdb/src/meta.ts#L310). This is causing a discrepancy between the versions that the workflows use and the version other parts of the workflow are using (e.g. Terraform).
This PR replaces the `sha` tag with a raw sha from the inputs.

ci: hardcode the real short SHA in Docker workflow

---

app/internal/config/autoload/laminas-developer-tools.local.php.dist
app/selfserve/config/autoload/laminas-developer-tools.local.php.dist

To workaround the `laminas-form` bug. This disables the events so no collectors are ran during event triggers. Can be re-enables when `laminas-form` is fixed.

fix: disable events in developer tools

---

app/api/config/autoload/local.php.dist
compose.yaml
docs/app/local-setup.md

mailpit container for local stack

feat: add mailpit container to compose stack and update docs

---

infra/docker/api/Dockerfile
infra/docker/api/php-fpm.conf
infra/docker/cli/Dockerfile
infra/docker/cli/php-fpm.conf
infra/docker/internal/Dockerfile
infra/docker/internal/php-fpm.conf
infra/docker/selfserve/Dockerfile
infra/docker/selfserve/php-fpm.conf

- Removes the PHP-FPM access logging to clear up the logging.
- Tweaks the process manager config to align with available resources. This is to trial with the non-functional tests.
`max_children` 
Equation: max memory / memory for single process 
4GB / 100MB (768MB is max PHP memory, but the app uses ~50MB on a typical request. 100MB was doubling the 50MB) = 40 (ish). This will be subject to change in the future as memory fluctuates.
`start_servers`
Equation: number of CPU cores * 4 
`min_spare_servers`
Equation: number of CPU cores * 2
`max_spare_servers`
Equation: number of CPU cores * 4

feat(docker): update PHP-FPM config

---

docs/app/local-setup.md
packages/local-refresh/src/index.ts

Extends the local setup guide to include a user/role/tenant map.

docs: add user, role and tenant map

---

app/selfserve/config/autoload/config-parameter.global.php

cast log level to Ints to work around error in nonprod
Related issue: [VOL-5765](https://dvsa.atlassian.net/browse/VOL-5765)

fix: cast str to int to satisfy typing on cpms client

---

app/api/module/DocumentShare/src/Service/ClientFactory.php
app/api/module/DocumentShare/src/Service/WebDavClient.php
app/api/test/module/DocumentShare/src/Service/ClientFactoryTest.php
app/api/test/module/DocumentShare/src/Service/WebDavClientTest.php

More debugging to try resolve the batch issue. It's going to be useful in the future so not temporary.

fix(api): handle errors better in `WebDavClient.php`

---

app/api/module/Email/view/email/cy_GB/html/licensing-information-continuation.phtml
app/api/module/Email/view/email/cy_GB/plain/licensing-information-continuation.phtml
app/api/module/Email/view/email/en_GB/html/licensing-information-continuation.phtml
app/api/module/Email/view/email/en_GB/plain/licensing-information-continuation.phtml

Update english and welsh templates to pull main body from a translation key for continuation information emails.
Related issue: [VOL-5756](https://dvsa.atlassian.net/browse/VOL-5756)

feat: change the continuation information email templates to use translation key

---

app/api/module/Api/src/Domain/QueryHandler/Messaging/ApplicationLicenceList/ByOrganisation.php
app/api/test/module/Api/src/Domain/QueryHandler/Messaging/ApplicationLicenceList/ByOrganisationTest.php

Add new statuses to include in messaging Licence/Application select dropdown on Create Message page.
Related issue: [VOL-5749](https://dvsa.atlassian.net/browse/VOL-5749)

feat: expand list of licence and application statuses in dropdown

---

infra/terraform/modules/service/README.md
infra/terraform/modules/service/batch.tf

The `ENVIRONMENT_NAME` variable is used to fetch parameters and secrets. Parameters and secrets are using the old environment names. 
The `legacy_environment` variable will contain that old name.

fix(terraform): use `legacy_environment` for environment name in the batch jobs

---

infra/docker/api/api.conf
infra/docker/internal/internal.conf
infra/docker/selfserve/selfserve.conf

The `/healthcheck` is used by the load balancers as a health check endpoint. The access log entry is not useful to anyone and causes lots of noise.
This PR excludes that endpoint from the access logs.

feat(docker): exclude `/healthcheck` from access logs

---

app/internal/module/Olcs/src/Controller/Auth/LoginController.php

On successful login, the user was being redirected back to the login page due to a bug. This was not noticeable as the login page would then redirect back to the dashboard. This fixes that unnecessary hop.
This is a bug as the hop wouldn't be triggered but we were trying to find `provider` in the API response, this is keyed as `Provider` instead.
https://github.com/dvsa/vol-app/pull/299/files#diff-dc696a5ccd77b1427575a83f6c3ab13433dde405bb961223735f87a82b400ac7L232

fix(internal): remove unnecessary login hop

---

infra/docker/selfserve/selfserve.conf

Removes the port from the redirect. This will fix Gov.UK One login on ECS.
Before on the redirect, it was trying to go to port `8080` (instead of 80).

fix(docker): add `port_in_redirect off` for One Login redirect

---

app/api/config/autoload/local.php.dist
infra/docker/selfserve/selfserve.conf

Forwards the query parameters when doing the GOV.UK OneLogin journey. This should hopefully fix the OneLogin issue in ECS.
This PR also updates the local config domains to be more accurate.

fix(docker): forward query parameters for GOV.UK OneLogin redirect

---

app/api/module/Auth/src/Adapter/LdapAdapter.php
app/api/module/Auth/src/Adapter/LdapAdapterFactory.php

The Ldap user objectClass requires a `sn` attribute passing. As this is only a local adapter, the `sn` is populated by the identifier to satisfy the schema.
The objectClass also doesn't have any user account control so that has been disabled.

fix(api): fix the local register journey while using LDAP

---

app/cdn/assets/_styles/components/modal.scss

Improvements for internal modals and alerts:
- Remove styling for absolute positioning for `.govuk-button-group`
- Removed superfluous bottom padding for the modal/alert.
Unrelated changes, are new git hooks to improve code styling being applied to changed files.
Related issue: https://dvsa.atlassian.net/browse/VOL-5734

fix: internal modal/alert button group position and modal bottom spacing

---

app/internal/config/autoload/local.php.dist
app/selfserve/config/autoload/local.php.dist

API Service Mapping Endpoints require URLs to be defined containing the Scheme, Host and Trailing Slash (as per existing postcode endpoint). 
Related issue: N/A

fix: local.php.dist api service mappings require full URLs

---

app/cdn/assets/_js/components/cascadeForm.js

JQ3 refactor fix
Related issue: [VOL-5715](https://dvsa.atlassian.net/browse/VOL-5715)
Related issue: [VOL-5713](https://dvsa.atlassian.net/browse/VOL-5713)

fix: refactor cascadeForm for JQ3

---

app/cdn/assets/_js/components/cascadeForm.js

Ensure that we remove display hardcoded style when unhiding elements using cascadeForm.
Related issue: https://dvsa.atlassian.net/browse/VOL-5744

fix: remove display hardcoded style when unhiding elements using cascadeForm

---

infra/terraform/environments/dev/main.tf
infra/terraform/environments/int/main.tf
infra/terraform/modules/service/README.md
infra/terraform/modules/service/cdn.tf

currently the CDN service module create a private route53 record which is causing some issues with the VOL app.
Related issue: [VOL-5755](https://dvsa.atlassian.net/browse/VOL-5755)

fix: alter CDN module to create public record rather than private

---

app/internal/config/autoload/config.global.php
app/selfserve/config/autoload/config.global.php

ECS environments defer to parameter `assets_url` for asset path.
Prerequisites:
https://github.com/dvsa/vol-terraform/pull/316
Related issue: https://dvsa.atlassian.net/browse/VOL-5788

fix: ecs environments defer to parameter assets_url for asset path

---

app/selfserve/module/Olcs/src/Form/Model/Fieldset/RegisterForOperator.php

Hotfix for missing use statement removed by IDE as "unused"

fix: ide removed an "unused" use statement. Adding back in as its essential

---

app/api/module/Api/src/Entity/Licence/Licence.php
app/api/module/Api/src/Service/Publication/Context/Variation/ConditionUndertaking.php
app/api/module/Api/src/Service/Submission/Sections/ConditionsAndUndertakings.php

`attached_to` col on `conditions_undertakings` is null by design for some rows. Some places in api we call `->getAttachedTo()->getId()` style chained methods. Added nullsafe to all the instances i could see calling `getAttachedTo()` on in a chain on a conditions undertakings entity.
Related issue: [VOL-5786](https://dvsa.atlassian.net/browse/VOL-5786)

fix: cater for some "attached_to" CU fields being null in the DB

---

app/internal/module/Olcs/src/FormService/Form/Lva/OperatingCentre/LvaOperatingCentre.php
app/internal/test/Olcs/src/FormService/Form/Lva/OperatingCentre/LvaOperatingCentreTest.php

Restores a radio option regarding sending evidence by post, for internal caseworker use only.
Related issue: [VOL-5814](https://dvsa.atlassian.net/browse/VOL-5814)

fix: restore "No (Operator to post)" radio for internal caseworker form

---

app/cdn/assets/_js/components/postcodeSearch.js

**Removes the .form__action field after failed postcode lookups.**
Failing to remove this field causes the form to repeat the same action (postcode lookup or address selection) when the user submits the form. This leads to a server error (500) on failure. By removing the field, users can manually enter their address without hindrance.
Related issue: https://dvsa.atlassian.net/browse/VOL-5807

fix: removes form__action field from failed postcode lookups

---

app/selfserve/module/Olcs/src/Controller/Search/SearchController.php
app/selfserve/test/Olcs/src/Controller/Search/SearchControllerTest.php

Resolves an RBAC issue allowing external access via direct URL to a search index intended only for some logged in users.
Related issue: [VOL-5828](https://dvsa.atlassian.net/browse/VOL-5828)

fix: external vehicle search access bug vol 5828

---

app/selfserve/module/Olcs/src/Form/Model/Form/Surrender/CurrentDiscs/CurrentDiscs.php

surrender journey button alignment
Related issue: [VOL-5836(https://dvsa.atlassian.net/browse/VOL-5836)

fix: surrender journey button alignment

---

app/selfserve/module/Olcs/src/Form/Model/Fieldset/OperatorRepresentation.php

Switches the radio buttons for the registration journey Operator Representation.
Related issue: https://dvsa.atlassian.net/browse/VOL-4705

fix: operator representation registration form radio options switched

---

app/selfserve/module/Olcs/src/Form/Model/Fieldset/RegisterForOperator.php

Updated register for operator form, business type field to have it's own translation key as the label is slightly varient to the standard.
Related issue: N/A

fix: updated businessType label for register for operator to have its own translation key

---

app/api/config/autoload/config.global.php
app/api/config/autoload/local.php.dist
app/api/module/Api/config/module.config.php
app/api/module/Api/src/Service/S3/S3ClientFactory.php
app/api/module/Cli/src/Domain/CommandHandler/AbstractDataExport.php
app/api/module/Cli/src/Domain/CommandHandler/DataDvaNiExport.php
app/api/module/Cli/src/Domain/CommandHandler/DataGovUkExport.php
app/api/test/module/Cli/src/Domain/CommandHandler/DataDvaNiExportTest.php
app/api/test/module/Cli/src/Domain/CommandHandler/DataGovUkExportTest.php

Update DataGov export to upload to S3 if given an s3:// URI
Related issue: [VOL-5819](https://dvsa.atlassian.net/browse/VOL-5819)

feat: update DataGovUkExport.php to upload to S3 bucket

---

.github/actions/get-app-version/action.yaml

Sanitize the version and ensure no slashes make it into returned sting.

fix: sanitize the returned version - dont return string with slashes in

---

.github/workflows/docker.yaml
.github/workflows/security-docker.yaml
.github/workflows/security-terraform.yaml
app/api/.gitignore
app/cdn/.gitignore
app/internal/.gitignore
app/selfserve/.gitignore

Alternate trivy DB repo to avoid ratelimit errors affecting multiple github actions users.

ci: specify a different repository for trivy-db to avoid ratelimit

---

app/api/module/Cli/src/Domain/CommandHandler/DataGovUkExport.php
app/api/test/module/Cli/src/Domain/CommandHandler/DataGovUkExportTest.php

Fix to ensure all report type call the uploadToS3 method

fix: two methods in DataGovUkExport did not call new parent uploadTos3

---

app/selfserve/module/Olcs/src/Controller/UserController.php
app/selfserve/test/Olcs/src/Controller/UserControllerTest.php

Ensures the Transport Consultant role is hidden from Add/Manage Users page when the feature toggle `transport_consultant_role` is **disabled**
Related issue: https://dvsa.atlassian.net/browse/VOL-4706

fix: add/manage user TC role hidden when TC toggle disabled

---

.github/workflows/cd.yaml

fix: properly call reuseable workflow in test-dev and test-int

---

.github/workflows/cd.yaml

Grant permissions needed by called workflow

fix: give e22 tests requisite permissions

---

.github/workflows/cd.yaml
.github/workflows/docker.yaml
.github/workflows/security-docker.yaml
.github/workflows/security-terraform.yaml
app/api/.gitignore
app/cdn/.gitignore
app/internal/.gitignore
app/selfserve/.gitignore

Specify trivy JAVA DB repository to avoid ghcr.io ratelimit errors

fix: use aws trivy java db registry avoid ratelimits

---

.github/workflows/cd.yaml
.github/workflows/deploy-environment.yaml
app/internal/.gitignore

add explicit success step for test runs

ci: make deployment status explicit for test step trigger debug

---

.github/workflows/cd.yaml
app/api/.gitignore

rollback it when tests fail explicitly or the called workflow dies some other way

chore: rollback int if e2etest workflow ends prematurely

---

.github/workflows/cd.yaml
.github/workflows/deploy-environment.yaml
app/api/.gitignore

use deploy-environment workflow for int rollback.

feat: use deploy-environment workflow for int rollback

---

app/api/module/Api/src/Entity/Organisation/AbstractOrganisation.php

Remove the option to change correspondence type on selfserve.
Internal users can still change the correspondence type if needed.
Related issue: [5774](https://dvsa.atlassian.net/browse/VOL-5774)
https://github.com/dvsa/olcs-etl/pull/70
https://github.com/dvsa/olcs-common/pull/176

feat: remove option to change correspondence type

---

infra/terraform/modules/service/ecs.tf

Despite the explicit dependency the TF apply is not correctly reporting health check status of service and cluster this is to apply workaround.

fix: remove healthcheck wait conditions

---

app/selfserve/module/Olcs/src/Controller/Lva/AbstractUndertakingsController.php

Ensures only Operator Transport Consultants are affected when it comes to the prevention of submitting an application or variation if an Operator Admin for the same organisation has never logged in.
Related issue: https://dvsa.atlassian.net/browse/VOL-5885

fix: only op-tc are affected by the submit app/var block op-adm check

---

app/api/composer.lock
app/api/module/Api/config/command-map.config.php
app/api/module/Api/config/validation-map/user.config.php
app/api/module/Api/src/Domain/CommandHandler/User/AgreeTerms.php
app/api/module/Api/src/Domain/CommandHandler/User/RegisterConsultantAndOperator.php
app/api/module/Api/src/Domain/CommandHandler/User/RegisterUserSelfserve.php
app/api/module/Api/src/Domain/QueryHandler/MyAccount/MyAccount.php
app/api/module/Api/src/Entity/User/AbstractUser.php
app/api/module/Api/src/Entity/User/User.php
app/api/test/module/Api/src/Domain/CommandHandler/User/AgreeTermsTest.php
app/api/test/module/Api/src/Domain/CommandHandler/User/RegisterConsultantAndOperatorTest.php
app/api/test/module/Api/src/Domain/CommandHandler/User/RegisterUserSelfserveTest.php
app/api/test/module/Api/src/Entity/User/UserEntityTest.php
app/internal/composer.lock
app/selfserve/composer.lock
app/selfserve/module/Olcs/Module.php
app/selfserve/module/Olcs/config/module.config.php
app/selfserve/module/Olcs/src/Controller/WelcomeController.php
app/selfserve/module/Olcs/src/Controller/WelcomeControllerFactory.php
app/selfserve/module/Olcs/src/Form/Model/Fieldset/AgreeTerms.php
app/selfserve/module/Olcs/src/Form/Model/Fieldset/ContinueOrSignOut.php
app/selfserve/module/Olcs/src/Form/Model/Form/AgreeTerms.php
app/selfserve/module/Olcs/src/Mvc/TermsAgreedListener.php
app/selfserve/module/Olcs/src/Mvc/TermsAgreedListenerFactory.php
app/selfserve/module/Olcs/view/pages/welcome.phtml
app/selfserve/test/Olcs/src/Mvc/TermsAgreedListenerTest.php

Welcome page now appears for external users to agree terms and conditions.
The following will need merging and dependencies bumped, before unit tests will pass:
[olcs-transfer](https://github.com/dvsa/olcs-transfer/pull/97)
Other related PRs:
[olcs-common](https://github.com/dvsa/olcs-common/pull/180)
[olcs-etl](https://github.com/dvsa/olcs-etl/pull/67)
Related issue: [VOL-5664](https://dvsa.atlassian.net/browse/VOL-5664)

feat: welcome page for external users with terms and conditions VOL-5664

---

app/api/module/Api/src/Domain/CommandHandler/User/DeleteUserSelfserve.php
app/api/module/Api/src/Domain/CommandHandler/User/UpdateUserSelfserve.php
app/api/module/Api/src/Domain/QueryHandler/MyAccount/MyAccount.php
app/api/module/Api/src/Entity/Organisation/Organisation.php
app/api/module/Api/src/Entity/User/User.php
app/api/test/module/Api/src/Domain/CommandHandler/User/DeleteUserSelfserveTest.php
app/api/test/module/Api/src/Domain/CommandHandler/User/UpdateUserSelfserveTest.php
app/api/test/module/Api/src/Domain/QueryHandler/MyAccount/MyAccountTest.php
app/api/test/module/Api/src/Entity/Organisation/OrganisationEntityTest.php
app/api/test/module/Api/src/Entity/User/UserEntityTest.php
app/selfserve/module/Olcs/src/Table/Tables/users.table.php

This PR deals with the selfserve portion of VOL-4718.
Also includes fixes as a result of the permissions reviewed in VOL-5796. Primarily this is preventing transport consultant role being incorrectly given to transport managers. Have also expanded unit tests in this area, in relation to who is and isn't considered an administrator, which was helpful for both tickets. 
Related issue: [VOL-4718](https://dvsa.atlassian.net/browse/VOL-4718)
Related issue: [VOL-5796](https://dvsa.atlassian.net/browse/VOL-5796)

feat: permission fixes, improve permission tests, faciltate check for last op admin user VOL-4718 VOL-5796

---

infra/terraform/accounts/prod/main.tf

Production Apply 
Related issue: https://dvsa.atlassian.net/browse/VOL-5261

feat: apply prod account

---

app/api/module/Api/src/Entity/User/User.php

Related issue: [VOL-5796](https://dvsa.atlassian.net/browse/VOL-5796)

fix: reinstate transport manager ability to have TC role

---

app/api/config/autoload/config.global.php

Remove placeholders for parameters which no longer exist in AWS Param store.

fix: remove placeholders that have been removed from paramstore

---

app/internal/composer.json
app/internal/composer.lock

Routing the Selfserve redirects through the index controller, has broken internal, which it turns doesn't have an index route. Locking Internal to the previous version of olcs-auth for now
Related issue: [VOL-5896](https://dvsa.atlassian.net/browse/VOL-5896)
Ticket for longer term fix: [VOL-5935](https://dvsa.atlassian.net/browse/VOL-5935)

fix: internal to use previous auth package for now VOL-5896

---

infra/terraform/modules/service/ecs.tf

Fixing the error:
The target group does not have an associated load balancer.
We are fixing this by removing the target group from the ecs service when the target group is not attached to a load balancer
Related issue: https://dvsa.atlassian.net/browse/VOL-5936

fix: 5936 lb toggle on ecs service

---

app/selfserve/module/Olcs/src/Controller/ConsultantRegistrationController.php
app/selfserve/module/Olcs/src/Controller/OperatorRegistrationController.php
app/selfserve/module/Olcs/src/Controller/WelcomeController.php
app/selfserve/module/Olcs/src/Controller/WelcomeControllerFactory.php
app/selfserve/module/Olcs/src/Form/Model/Form/AgreeTerms.php

Terms and conditions links have the URL merged into a translation key, this wasn't happening on the new TC journey.
Related issue: [VOL-5943](https://dvsa.atlassian.net/browse/VOL-5943)

fix: terms and conditions link populated on TC journey VOL-5943

---

app/api/config/autoload/config.global.php

fix: replace inr/natreg config placeholders

---

app/cdn/public/tinymce/plugins/spellchecker/OlcsEngine.php

The default language for spellchecking is now en_GB. It should be noted that the version of TinyMCE and associated spellchecker are very old, dating back to 2015 and 2014 respectively. We should do something about this going forward.
Related issue: [VOL-5907](https://dvsa.atlassian.net/browse/VOL-5907)

fix: default language for spellcheck to en_GB

---

app/api/module/Email/view/email/en_GB/plain/user-registered-tc.phtml

This looks like a copy/paste error where HTML close paragraph tag has been left in the plain text version of the email. Needs removing as it has the effect of being added onto the end of the username.

fix: remove </p> being added to end of usernames (tc user registration email)

---

docs/rfc/rfc-007-prereleases.md
prerelease-config.json

Related issue: [VOL-5867](https://dvsa.atlassian.net/browse/VOL-5867)

feat: rfc on proposed pre-release workflow - reference implementation in poc repo

---

.github/workflows/cd.yaml
.github/workflows/ci.yaml
.github/workflows/php.yaml
infra/docker/liquibase/Dockerfile

Ensure pre-release versions dont progress to prod, split out 
Related issue: [VOL-5907](https://dvsa.atlassian.net/browse/VOL-5907)
Related issue: [VOL-5972](https://dvsa.atlassian.net/browse/VOL-5972)

feat: add prerlease check before prod deploy, split regression into selfserve/internal steps

---

infra/terraform/modules/service/batch-liquibase.tf

Addressing issue in previous terraform apply:
ValueFrom is not an Arn for System Manager Parameter or Secret Manager secret
Related issue: https://dvsa.atlassian.net/browse/VOL-5954

fix: 5954 liquidate batch job secret arn

---

app/api/module/Api/src/Domain/QueryHandler/Workshop/Workshop.php

Quick addendum, it appears we're being passed the licence id as a string here, so relaxing the type check. Like most of the DTOs, ideally in the long run we'd add a filter on the query itself to always force int or null, but this requires testing everywhere it's used etc.
Related issue: [VOL-5982](https://dvsa.atlassian.net/browse/VOL-5982)

fix: relax licence type check when retrieving workshop, query is giving id as a string

---

.github/workflows/cd.yaml

submit_job param not present on workflow_call, only dispatch. Removed.

fix: remove param being passed to workflow_call only valid for dispatch

---

.github/workflows/run-liquibase.yaml

batch definition requires share params to be set on job submission.

fix: specify scheduling params for liquibase batch job

---

.github/workflows/cd.yaml
app/api/.gitignore
infra/docker/search/Dockerfile

dont require a nonprod tf run (as it can be skipped) for liquibase migration to run

chore: run liquibase if app is built but acct terraform was skipped

---

app/selfserve/module/Olcs/src/Controller/OperatorRegistrationController.php

- Fixed error handling for when a user tries to register on self serve and uses  an already existing username 
Related issue: VOL-5994 https://dvsa.atlassian.net/browse/VOL-5994

fix: error handling for registration

---

app/selfserve/module/Olcs/src/Controller/OperatorRegistrationController.php

Fixed error handling for when a user tries to register on self serve and uses an already existing username.
Related issue: VOL-5994 https://dvsa.atlassian.net/browse/VOL-5994

fix: error handling for SS registration

---

infra/terraform/modules/service/batch.tf

fix batch job default command so that full command is provided. To fix the error:
/usr/local/bin/docker-php-entrypoint: exec: line 9: queue:process-queue: not found

fix: set job command default option

---

app/selfserve/module/Olcs/view/pages/application-summary.phtml

Make sure that the birth date formatting is `DD-MM-YYYY` for transport managers, on an application overview.
Related issue: [6050](https://dvsa.atlassian.net/browse/VOL-6050)

fix: formatting of tm birth date on application overview

---

.github/workflows/cd.yaml

Attempt to avoid liquibase being skipped after dev terraform

fix: try stop liquibase being skipped despite terraform-env-dev completing

---

infra/terraform/modules/service/batch-monitoring.tf
infra/terraform/modules/service/batch.tf

fix metric filter name to be different per job

fix: 5912 metric filter name

---

.github/workflows/docker.yaml
app/api/.snyk

Suppres synk error for a little longer, and correct a URI to pull down correct binary for new runner arch.

chore: supress twig snyk error - pull correct dep for new runner arch

---

app/api/module/Api/src/Service/Ebsr/FileProcessor.php

Try creating required EBSR sub tmp folder before giving up

fix: try creating EBSR sub-tmp folder if not exists

---

docs/pre-release-process.md
docs/release-process.md

docs for containers release process, including optional pre-release flow for iterating on rc versions
Related issue: [VOL-5622](https://dvsa.atlassian.net/browse/VOL-5622)
[VOL-5622]: https://dvsa.atlassian.net/browse/VOL-5622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: update deployment process docs vol 5622

---

app/api/module/Api/src/Domain/CommandHandler/Cases/Si/ComplianceEpisode.php
app/api/test/module/Api/src/Domain/CommandHandler/Cases/Si/ComplianceEpisodeTest.php

Tasks for erru cases have always had the action date 7 days in the future. While testing this @culshawn has requested this be changed to the same day the case was created.
Related issue: [VOL-5817](https://dvsa.atlassian.net/browse/VOL-5817)
[VOL-5817]: https://dvsa.atlassian.net/browse/VOL-5817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: erru case tasks have action date the same as case creation date VOL-5817

---

app/internal/composer.json
app/internal/composer.lock
app/selfserve/composer.json
app/selfserve/composer.lock

chore: bump `olcs-common` to 7.17.2

---

app/api/module/Api/src/Entity/Bus/BusReg.php

Quick addendum to this ticket. Bus variation and cancellation records are created by making a copy of the previous version, with some fields cleared. The application complete date is now one of the cleared fields.
Related issue: [VOL-6054](https://dvsa.atlassian.net/browse/VOL-6054)
[VOL-6054]: https://dvsa.atlassian.net/browse/VOL-6054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: application complete date no longer copied to bus variations VOL-6054

---

infra/terraform/modules/account/ecr.tf

… quickly
Initially the lifecycle policy for the ECR was set to keep the last 5 artefacts however, we create about 5 artefacts each time we create a container meaning there isn't scope for previous container image in the ECR's.
Related issue:

fix: increase lifecycle policy to prevent images being overwritten

---

.github/workflows/cd.yaml

Removes :latest tagged images in prod ecr prior to pushing new container images to avoid errors on the immutable repos

fix: delete prod ecr :latest tags before pushing as repos are immutable

---

infra/terraform/modules/service/ecs.tf

logic to register ECS service with target group regardless of listener_rule_enable boolean.

fix: amend target group logic to register with load balancer

---

app/api/config/autoload/config.global.php

Properly set the cdn style assets link in api as well as int/sserve for some api generated markup
Related issue: [VOL-6358](https://dvsa.atlassian.net/browse/VOL-6358)
[VOL-6358]: https://dvsa.atlassian.net/browse/VOL-6358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: resolve styling issues on some snapshots

---

infra/docker/internal/internal.conf

Update internal nginx config to allow split screen embed functionality from SAMEORIGIN
Related issue: [VOL-6356](https://dvsa.atlassian.net/browse/VOL-6356)
[VOL-6356]: https://dvsa.atlassian.net/browse/VOL-6356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: allow sameorigin frame embeds to fix Split Screen functionality

---

.github/workflows/assets.yaml

Adds a push option to workflow dispatch of assets workflow.

fix: add push option to assets workflow dispatch

---

app/internal/composer.lock
app/selfserve/composer.lock

Added MPRS link to Safety Inspectors stage of application journey.
Bumped olcs-common to reflect changes on selfserve and internal.
See:
https://github.com/dvsa/olcs-common/pull/231
https://github.com/dvsa/olcs-etl/pull/91
https://github.com/dvsa/olcs-common/pull/232
Related issue: https://dvsa.atlassian.net/browse/VOL-6300

feat: add link to mprs

---

app/api/module/Api/config/validation-map/side-effects.config.php
app/api/module/Api/src/Domain/CommandHandler/Application/UpdateApplicationCompletion.php

Related issue: [VOL-5882](https://dvsa.atlassian.net/browse/VOL-5882)
[VOL-5882]: https://dvsa.atlassian.net/browse/VOL-5882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: remove reference to the old update command for vehicles declarations

---

app/api/module/Api/src/Domain/CommandHandler/Application/UpdateVariationCompletion.php

Related issue: [VOL-6504](https://dvsa.atlassian.net/browse/VOL-6504)
[VOL-6504]: https://dvsa.atlassian.net/browse/VOL-6504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: psv variations no longer show steps required for only restricted licences VOL-6504

---

.github/workflows/cd.yaml
.github/workflows/php.yaml

Add step to docker/php build process to bake the version number being built into the 3 apps
Related issue: [VOL-6567](https://dvsa.atlassian.net/browse/VOL-6567)
[VOL-6567]: https://dvsa.atlassian.net/browse/VOL-6567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: bake versions into container images built by the cd pipeline

---

app/api/.gitignore
infra/terraform/environments/dev/main.tf
infra/terraform/environments/int/main.tf
infra/terraform/environments/prep/main.tf
infra/terraform/environments/prod/main.tf
infra/terraform/modules/service/ecs.tf

The pdf-converter references an external source for the container ref which the service/task will not have access to. Corrected to use a pull-through cache in ECR.
I have also bumped .gitignore to trigger a new container build as requested.

fix: renderer container repo

---

app/api/module/Snapshot/view/partials/continuation-conditions-undertakings.phtml

Related issue: [VOL-6569](https://dvsa.atlassian.net/browse/VOL-6569)
[VOL-6569]: https://dvsa.atlassian.net/browse/VOL-6569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: continuations missing condition or undertaking info, now display correctly VOL-6569

---

infra/docker/cli/Dockerfile

Bash jobs weren't running correctly as the bash shell was not installed on the cli container

fix: batch bash jobs
